version: '3'
services:
  example-postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    environment:
      LANG: ja_JP.utf8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
